setup cypress configuration
veroggu/cypress-training pull request #3
Opened 2021-03-26 00:56 UTC by veroggu

2021-03-26 01:30 UTC, holgiosalos approved these changes

2021-03-26 02:15 UTC, renardete requested changes

2021-03-26 02:15 UTC, renardete commented on cypress/fixtures/profile.json
> +{
You could delete this file.

2021-03-26 02:15 UTC, renardete commented on cypress/fixtures/users.json
> +[
you could delete this file

2021-03-31 12:43 UTC, holgiosalos approved these changes

2021-03-31 14:46 UTC, gipesoft-one approved these changes

2021-03-31 14:47 UTC, renardete approved these changes

2021-03-31 20:14 UTC, holgiosalos commented
Hi @veroggu your PR is now unblocked for squash and merge it... once you merge this one, please update the setuptypescript branch with this changes

2021-04-02 21:06 UTC, merged